version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: med_app_db
      POSTGRES_USER: doctor
      POSTGRES_PASSWORD: peniceline
    ports:
      - "5432:5432"


  projecta:
    build:
      context: ./ProjectA
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ProjectA:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ProjectA.settings
    depends_on:
      - db