# Generated by Django 5.0.6 on 2024-07-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_message'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
