# Generated by Django 5.0.6 on 2024-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
