# Generated by Django 5.0.6 on 2024-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('consultations', '0008_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(default=1, related_name='customuser_set', to='auth.group'),
        ),
    ]
