name: Deploy Django project to PythonAnywhere
on:
  push:
    branches:
      - deploy_iter_three_mysql

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PA_UPDATE.sh on server
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_API_USERNAME: ${{ secrets.PA_API_USERNAME }}
        run: |
          echo "Token: $PA_API_TOKEN"
          echo "Username: $PA_API_USERNAME"
          curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{'input': 'bash PA_UPDATE.sh\n'}" \
          "https://www.pythonanywhere.com/api/v0/user/$PA_API_USERNAME/consoles/35065416/send_input"

      - name: reboot server
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_API_USERNAME: ${{ secrets.PA_API_USERNAME }}
        run: |
          echo "Token: $PA_API_TOKEN"
          echo "Username: $PA_API_USERNAME"
          curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
          -H "Content-Type: application/json" \
          "https://www.pythonanywhere.com/api/v0/user/xammax/webapps/xammax.pythonanywhere.com/reload/"
